# Generated by Django 4.1.9 on 2023-05-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0026_kvadratnaizracunajnicle_kvadratnaneenacba_neenacba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsotaGeometrijskega',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('podan_splosni_clen', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=True, help_text='Ali je podan splošni člen zaporedja?', verbose_name='podan splosni clen')),
            ],
            options={
                'verbose_name': 'Zaporedja / vsota prvih n členov geometrijskega zaporedja',
            },
            bases=('problems.problem',),
        ),
    ]
