# Generated by Django 4.1.9 on 2023-05-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_vsotageometrijskega'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsotaGeometrijskeVrste',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('lazji_podatki', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=True, verbose_name='lazji podatki')),
            ],
            options={
                'verbose_name': 'Zaporedja / vsota geometrijske vrste',
            },
            bases=('problems.problem',),
        ),
    ]
