# Generated by Django 4.1.9 on 2023-05-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0028_vsotageometrijskevrste'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrviCleniGeometrijskega',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('racionalne_vrednosti', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, help_text='Ali naj bodo vključene racionalne vrednosti?', verbose_name='racionalne vrednosti')),
            ],
            options={
                'verbose_name': 'Zaporedja / prvi člen in količnik geometrijskega',
            },
            bases=('problems.problem',),
        ),
        migrations.AlterField(
            model_name='vsotageometrijskevrste',
            name='lazji_podatki',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=True, help_text='Ali naj bodo v nalogi lažji podatki?', verbose_name='lazji podatki'),
        ),
    ]
